config/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myreactor.urls", namespace="myreactor")),
]

myreactor/urls.py
from django.urls import path
from . import views

app_name = "myreactor"

urlpatterns = [
    # post views
    path("", views.index, name="index"),
    path("restart/", views.restart, name="restart"),
    path("play/data/", views.play_data, name="play_data"),
    path("play/<int:playerid>/", views.play, name="play"),
    path("play/data/score/", views.score, name="score"),
    path("info/<int:playerid>/", views.info, name="info"),
    path("register/", views.register, name="register"),
    path("reset/", views.reset, name="reset"),
]

casestudy/models.py
from django.db import models


class CaseStudy(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

myreactor/casestudy/models.py
from django.db import models

class CaseStudy(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    

myreactor/models.py
from django.db import models

# Create your models here.

myreactor/players/models.py
from django.db import models


class Player(models.Model):
    name = models.CharField(
        verbose_name="Votre nom", max_length=255, blank=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

myreactor/scores/models.py
from django.db import models

from ..casestudy.models import CaseStudy
from ..players.models import Player


class Score(models.Model):
    total_reaction_time = models.FloatField(null=False)
    final_conversion = models.FloatField(null=False)
    player = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name="scores"
    )

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"({self.player}, {self.total_reaction_time}, {self.final_conversion:.2f})"

myreactor/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .players.models import Player


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ("name",)


class ResetForm(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput, label="Mot de passe", required=True
    )

    def clean_password(self):
        password = self.cleaned_data["password"]
        if password != "chemtech":
            raise ValidationError("Mot de passe incorrect")
        return password

myreactor/casestudy/views.py
from django.shortcuts import render

# Create your views here.

myreactor/players/views.py
from django.shortcuts import render

# Create your views here.

myreactor/scores/views.py
from django.shortcuts import render

# Create your views here.

myreactor/views.py
import json

import numpy as np
from django.http import JsonResponse
from django.shortcuts import render, redirect

from .forms import PlayerForm, ResetForm
from .players.models import Player
from .scores.models import Score

from .casestudy import solvers


def index(request):
    form = PlayerForm()

    best_scores = Score.objects.order_by("total_reaction_time")[:5]

    return render(
        request, "myreactor/index.html", {"form": form, "scores": best_scores}
    )


def play(request, playerid):
    data = {
        "CA": solvers.CA0,
        "CB": solvers.CB0,
        "CC": solvers.CC0,
        "CD": solvers.CD0,
        "CE": solvers.CE0,
        "T": solvers.T0,
        "Tj": solvers.Tj0,
        "Tjset": solvers.Tjset0,
        "U": solvers.U0,
        "X": 0,
        "playerid": playerid,
    }

    best_scores = Score.objects.order_by("total_reaction_time")[:5]

    return render(
        request,
        "myreactor/play.html",
        {"data": json.dumps(data), "scores": best_scores},
    )


def info(request, playerid):
    best_scores = Score.objects.order_by("total_reaction_time")[:5]

    return render(
        request,
        "myreactor/info.html",
        {"playerid": playerid, "scores": best_scores},
    )


def register(request):
    if request.method == "POST":
        form = PlayerForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]

            player, created = Player.objects.get_or_create(name=name)
            return redirect("myreactor:info", playerid=player.id)
    return redirect("myreactor:index")


def play_data(request):
    solvers.Dt = 60
    data = {k: float(i) for k, i in request.POST.dict().items()}
    data["playerid"] = int(data["playerid"])
    while True:
        try:
            data = solvers.morton(**data)
        except Exception as e:
            solvers.Dt = solvers.Dt / 1.5
            if solvers.Dt < 1e-6:
                break
        else:
            break
    return JsonResponse(data)


def reset(request):
    if request.method == "POST":
        form = ResetForm(request.POST)
        if form.is_valid():
            Score.objects.all().delete()
            Player.objects.all().delete()
            return redirect("myreactor:index")
    else:
        form = ResetForm()
    return render(request, "myreactor/reset.html", context={"form": form})


def score(request):
    data = {k: i for k, i in request.POST.dict().items()}
    player = Player.objects.get(pk=int(data["player"]))
    score = Score(
        total_reaction_time=int(data["t"]),
        final_conversion=float(data["X"]),
        player=player,
    )
    score.save()
    return JsonResponse({"status": "recorded", "error": False})


def restart(request):
    return redirect("myreactor:index")

myreactor/templates/myreactor/base.html
{% load static %}
<!doctype html>
<html lang="fr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Orbitron:400,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">

    <title>myReactor | HEIA-FR | ChemTech</title>
  </head>
  <body>

    {% block header %}
    <header id="header" class="jumbotron">
        <a href="/">
          <img src="{% static 'img/logo.png' %}" width="250px">
        </a>
        <ol class="scores">
          {% for score in scores %}
          <li {% if forloop.first %}class="first"{% endif %}>{{score.player.name }}: {{ score.total_reaction_time }} min</li>
          {% empty %}
          {% endfor %}
        </ol>
    </header>
    {% endblock %}
    
    <main id="main">
      {% block main %}{% endblock %}
    </main>
        
    {% block footer %}
    <footer id="footer" class="d-flex justify-content-between">
        <p>&copy; 2025 Institut ChemTech - Haute Ecole d'Ingénierie et d'Architecture de Fribourg</p>
        <div><a href="{% url 'myreactor:reset' %}" class="text-secondary">Réinitialiser les scores</a></div>
    </footer>
    {% endblock %}

    {% block modals %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    {% comment %} <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script> {% endcomment %}
    {% block bottom_scripts %}{% endblock %}
  </body>
</html>

myreactor/templates/myreactor/index.html
{% extends 'myreactor/base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Jeu: pilotez le réacteur chimique qui explosa lors de l'accident de Morton en 1998</h1>
            </div>
        </div>
        <div class="row">
            <div class="start-button col-12">
                <button type="button" class="btn btn-success"  data-toggle="modal" data-target="#name-registration">Commencer</button>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p class="reaction">
                    <img src="{% static 'img/reaction.png' %}">
                </p>
                <p class="accident">
                    Entre 1990 et 1998, Morton International Inc. a produit un colorant pour l'industrie pétrolière appelé 
                    Automate Jaune 96 (Automate Yellow AY96). Les études thermiques réalisées entre 1986 et 1990 ont montré 
                    un comportement lent et exothermique (dégage de la chaleur). La réaction de synthèse est suivie d'une décomposition hautement 
                    exothermique du produit. Cette dernière réaction a été sous-estimée lors la mise à l'échelle, car l'entreprise 
                    a continué d'augmenter le volume de production tout en conservant les mêmes conditions. Elle a même passé d'un procédé 
                    semi-continu à un procédé discontinu. De plus, de nombreux écarts de température ont été observés dans la cuve 
                    du réacteur de 7,6 m3 et ont signalés par les opérateurs. Malgré les commentaires de plusieurs superviseurs, les 
                    écarts de température ont été ignorés. Les fortes hausses de température constituaient un problème de qualité 
                    et non un problème de sécurité. Le 4 août 1998, sur le site de Paterson (New Jersey, USA), une explosion et 
                    un incendie se sont produits. La décomposition de l'AY96 a causé de nombreux dommages, le rejet de matières 
                    dangereuses et a blessé 9 employés, y compris deux d'entre eux sérieusement (US Chemical Safety and Hazard 
                    Investigation Board, 2000).
                </p>
            </div>
        </div>
    </div>

    
{% endblock %}

{% block modals %}
<div id="name-registration" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Pour essayer, indiquez votre nom</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        
        <form method="post" action="/register/">
            <div class="modal-body">
                {% csrf_token %}
                {{ form|crispy }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Abandonner</button>
                <button type="submit" class="btn btn-success">Continuer</button>
            </div>
        </form>
        

        </div>
        </div>
    </div>
</div>
{% endblock modals %}

myreactor/templates/myreactor/info.html
{% extends 'myreactor/base.html' %}

{% load static %}

{% block main %}
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-6">
      <h3>Comment se présente le réacteur?</h3>
      <p>Vous allez contrôler la température du réacteur suivant. La 
      <strong style="color:red">partie rouge</strong> représente le manteau externe 
      par lequel vous allez chauffer en manipulant la température (T<sub>j</sub>).
      La <strong style="color:#069">partie bleue</strong> représente le mélange où
      a lieu <strong>la réaction chimique</strong> et dont la température est 
      T<sub>r</sub>. Pour <strong>chauffer</strong>, T<sub>j</sub> doit être plus grand que 
      T<sub>r</sub> et inversement pour <strong>refoidir</strong>.</p>
      <p><center><img src="{% static 'img/reacteur.png' %}" width="200px"></center></p>
    </div>
    <div class="col-12 col-lg-6">
      <p>Pour <strong>chauffer ou refroidir</strong> la cuve, vos boutons
      de contrôle sont:</p>
      <p><center><img src="{% static 'img/cool-heat-buttons.png' %}" width="400px"></center></p>
      <p>Vous pouvez également contrôler la température du manteau à l'aide des 
      flèches directionnelles du clavier:</p>
      <p><center><img src="{% static 'img/fleches.png' %}" width="400px"></center></p>
    <div>
  </div>
  <div class="row">
    <div class="col-12">
      <p>
        <form method="post" action="{% url 'myreactor:play' playerid=playerid %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-success" style="width: 100%">C'est parti!</button>
        </form>
      </p>
    </div>
  </div>
</div>
{% endblock %}

myreactor/templates/myreactor/play.html
{% extends 'myreactor/base.html' %}

{% load static %}

{% block header %}
<header id="header" class="jumbotron d-flex justify-content-between align-items-center">
  <a href="/" class="align-self-start">
    <img src="{% static 'img/logo.png' %}" width="250px">
  </a>
  {% comment %} <a href="/">
    <img class="m-4" src="{% static 'img/reaction.png' %}" width="600px">
  </a> {% endcomment %}
  <ol class="scores">
    {% for score in scores %}
    <li {% if forloop.first %}class="first"{% endif %}>{{score.player.name }}: {{ score.total_reaction_time }} min</li>
    {% empty %}
    {% endfor %}
  </ol>
</header>
{% endblock %}




{% block main %}
<div id="dashboard" class="dashboard">
    <div id="plots" class="plots" data-url="{% url 'myreactor:play_data' %}">
        <div id="plot-temperatures" class="plot plot-temperatures"></div>
        <div id="plot-concentrations" class="plot plot-concentrations"></div>
    </div>
    <div id="displays" class="displays">
        <div id="tj-display" class="display">T<sub>j</sub> = 30 °C</div>
        <div id="X-display" class="display">T<sub>r</sub> = 30 °C</div>
    </div>
    <div id="temperature-btns" class="temperature-btns">
        <button id="cool-btn" type="button" class="btn btn-success temperature-btn">Refroidir</button>
        <button id="heat-btn" type="button" class="btn btn-danger temperature-btn">Chauffer</button>
    </div>
</div>

{% endblock %}

{% block modals %}
<div id="runaway" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Votre réacteur s'est emballé et a explosé!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        
      <div class="modal-body">
        <p>Lorsque la température d'un réacteur ne peut être maîtrisée, on 
          parle <strong>d'emballement thermique</strong> ou de 
          <strong>runaway</strong>.</p>
          <p><center><img src="{% static 'img/morton.jpg' %}" width="400px"></center></p>
          <p>La maîtrise de ces risques a donné naissance à deux sciences: la
          <strong>sécurité thermique des procédés chimiques et le concept 
          sécurité des installations</strong>. Ces
          pratiques aide <strong>l'ingénieur chimiste</strong> à identifier
          les conditions sûres pour l'opération des réacteurs chimiques et
          fait aujourd'hui de la chimie un des secteurs industriels les
          plus sûrs (risque statistiquement comparable à une activité de
          bureau dans l'administration).</p>
      </div>
      <div class="modal-footer">
          <form action="/restart/">
          <button type="submit" class="btn btn-success">Recommencer</button>
          </form>
      </div>

    </div>
  </div>
</div>

<div id="victoire" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Félicitations, objectif atteint!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
        
      <div class="modal-body">
        <p>Vous avez atteint la conversion désirée (X = 95%) tout en maîtrisant
        les conditions de réaction. Quel champion(-ne)!</p>
        <p><center><img src="{% static 'img/coupe.png' %}" width="200px"></center></p>
        <p>En appliquant les connaissances en génie chimique apprises à
        la HEIA-FR, vous avez peut-être la possibilité d'améliorer encore
        votre performance.</p>
      </div>
      <div class="modal-footer">
        <form action="/restart/">
        <button id="victoire-btn" type="submit" class="btn btn-success">Recommencer</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block footer %}
<audio id="runaway-sound">
  <source src="{% static 'sounds/explosion.mp3' %}" type="audio/mpeg">
  Ton navigateur ne supporte pas l'audio HTML5.
</audio>
<audio id="champions-sound">
  <source src="{% static 'sounds/champions.mp3' %}" type="audio/mpeg">
  Ton navigateur ne supporte pas l'audio HTML5.
</audio>
{% endblock footer %}

{% block bottom_scripts %}
<script>

    var data = {{ data|safe }};

    t_failure = Math.floor(Math.random() * 900);
    t_failure_end = t_failure + 10 + Math.floor(Math.random() * 30);

    // Plots
    var temperatures = Highcharts.chart('plot-temperatures', {

        title: {
          text: 'Suivi des températures'
        },

        xAxis: {
          title: {
            text: 'temps (min)'
          }
        },

        yAxis: {
          title: {
            text: 'température (°C)'
          }
        },
        legend: {
          layout: 'horizontal',
          align: 'left',
          verticalAlign: 'top'
        },

        plotOptions: {
          series: {
            label: {
              connectorAllowed: false
            },
            marker: {
                enabled: false
            },
            pointStart: 0
          }
        },

        series: [{
          name: 'Tr',
          color: '#069',
          data: []
        }, {
          name: 'Tj',
          color: '#dc3545',
          data: []
        }, {
          name: 'Tj,commande',
          color: '#000',
          data: []
        }],

        responsive: {
          rules: [{
            condition: {
              maxWidth: 500
            },
            chartOptions: {
              legend: {
                layout: 'horizontal',
                align: 'center',
                verticalAlign: 'bottom'
              }
            }
          }]
        }

      });

      var concentrations = Highcharts.chart('plot-concentrations', {

        title: {
          text: 'Suivi des concentrations'
        },

        xAxis: {
          title: {
            text: 'temps (min)'
          }
        },

        yAxis: {
          title: {
            text: 'Concentrations (mol/g)'
          }
        },
        legend: {
          layout: 'horizontal',
          align: 'left',
          verticalAlign: 'top'
        },

        plotOptions: {
          series: {
            label: {
              connectorAllowed: false
            },
            marker: {
                enabled: false
            },
            pointStart: 0
          }
        },

        series: [{
          name: '2-EHA (A)',
          data: []
        }, {
          name: 'o-NCB (B)',
          data: []
        }, {
          name: 'AY96 (C)',
          data: []
        }, {
          name: 'HCl (D)',
          data: []
        }, {
          name: 'Autres (E)',
          data: []
        }],

        responsive: {
          rules: [{
            condition: {
              maxWidth: 500
            },
            chartOptions: {
              legend: {
                layout: 'horizontal',
                align: 'center',
                verticalAlign: 'bottom'
              }
            }
          }]
        }

      });

      // Quand la modale #runaway s'affiche (avec Bootstrap)
      $('#runaway').on('shown.bs.modal', function () {
          const sound = document.getElementById('runaway-sound');
          sound.play().catch(function(e){
              console.log("Lecture du son bloquée :", e);
          });
      });

      // Quand la modale #victoire s'affiche (avec Bootstrap)
      $('#victoire').on('shown.bs.modal', function () {
        const sound = document.getElementById('champions-sound');
        sound.play().catch(function(e){
            console.log("Lecture du son bloquée :", e);
        });
    });
</script>
<script src="{% static "js/play.js" %}"></script>
{% endblock %}

myreactor/templates/myreactor/playground.html
{% extends 'myreactor/base.html' %}

{% load static %}

{% block header %}
{% endblock %}

{% block main %}
{% endblock %}

{% block fooder %}
    <p>&copy;2019-2024 Institut ChemTech - Haute Ecole d'Ingénierie et d'Architecture de Fribourg</p>
{% endblock %}

myreactor/templates/myreactor/reset.html
{% extends 'myreactor/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Réinitialisation des scores</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div>
                    <button type="submit" class="btn btn-danger">Réinitialiser</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main %}